apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 797260140066.dkr.ecr.ap-south-1.amazonaws.com/three-tier-backend:REPLACE_ME
          ports:
            - containerPort: 3500
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/todo?authSource=admin
            - name: USE_DB_AUTH
              value: "true"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          startupProbe:
            httpGet:
              path: /started
              port: 3500
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 3500
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3500
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: three-tier
spec:
  selector:
    app: backend
  ports:
    - port: 3500
      targetPort: 3500